name: Test 1

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"

      - name: Touch file
        run: touch test.txt

      - name: Set text
        run: echo "Hello, world!" >> test.txt

      - name: Read file
        run: cat test.txt

  other:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2            

      - name: LS
        uses: ././.github/actions/my-action
        with: 
          message: "Custom message"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: latest

      - name: Node version
        run: node -v
            
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Php version
        run: php --version