name: Test 1

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"

      - name: Touch file
        run: touch test.txt

      - name: Set text
        run: echo "Hello, world!" >> test.txt

      - name: Read file
        run: cat test.txt

  other:
    runs-on: ubuntu-latest
    steps:
      - name: LS
        run: ls -al
